Repository snack-25/front, pull requests merged in 2025-03, with the labels that each got.

#3 🐛 fix(commitlint): commitlint 규칙 완화
  commitlint.config.js
Labels: bug, FE

#4 ⬆️ chore(deps): TailwindCSS 버전 업데이트(4.0.9 -> 4.0.10)
  .lintstagedrc.js
  commitlint.config.js
  package.json
  pnpm-lock.yaml
  stylelint.config.mjs
Labels: bug, FE

#6 🐛 fix(scripts): preinstall 스크립트에서 오류 발생 시 종료 코드 추가
  package.json
Labels: bug, chore, FE

#9 Chore(UI)/7 update home page
  .gitignore
  components.json
  pnpm-lock.yaml
  public/icon/flat/cart-outlined-md.svg
  public/icon/flat/cart-outlined-sm.svg
  public/icon/flat/cart-solid-md.svg
  public/icon/flat/cart-solid-sm.svg
  public/icon/flat/close-circle-md.svg
  public/icon/flat/close-circle-sm.svg
  public/icon/flat/like-active-lg.svg
  public/icon/flat/like-active-md.svg
  public/icon/flat/like-active-sm.svg
  public/icon/flat/like-default-lg.svg
  public/icon/flat/like-default-md.svg
  public/icon/flat/like-default-sm.svg
  public/icon/flat/link-md.svg
  public/icon/flat/link-sm.svg
  public/icon/flat/profile-md.svg
  public/icon/flat/profile-sm.svg
  public/icon/lined/chevron-down-md.svg
  public/icon/lined/chevron-down-sm.svg
  public/icon/lined/chevron-down-xs.svg
  public/icon/lined/chevron-left-md.svg
  public/icon/lined/chevron-left-sm.svg
  public/icon/lined/chevron-left-thin-sm.svg
  public/icon/lined/chevron-right-md.svg
  public/icon/lined/chevron-right-sm.svg
  public/icon/lined/chevron-right-thin-sm.svg
  public/icon/lined/chevron-right-xs.svg
  public/icon/lined/chevron-up-md.svg
  public/icon/lined/chevron-up-sm.svg
  public/icon/lined/chevron-up-xs.svg
  public/icon/lined/close-md.svg
  public/icon/lined/close-sm.svg
  public/icon/lined/hamburger-menu-md.svg
  public/icon/lined/hamburger-menu-sm.svg
  public/icon/lined/kebab-menu-md.svg
  public/icon/lined/kebab-menu-sm.svg
  public/icon/lined/plus-md.svg
  public/icon/lined/plus-sm.svg
  public/icon/lined/search-md.svg
  public/icon/lined/search-sm.svg
  public/icon/lined/visibility-off.svg
  public/icon/lined/visibility-on.svg
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
  tsconfig.json
Labels: bug, FE, ui/ux, page

#14 Fix(package)/13-update-package-json
  package.json
  src/app/globals.css
  src/app/playground/page.tsx
Labels: chore, FE

#22 ✨ feat(shared): add shared-gnb
  package.json
  pnpm-lock.yaml
  public/img/gnb/gnb-logo-primary.svg
  src/app/globals.css
  src/app/playground/page.tsx
  src/components/gnb/Header.tsx
  src/components/gnb/HeaderMenu.tsx
  src/components/ui/Dropdown-Menu.tsx
Labels: feat, FE

#23 ✨ feat(Header): add Header to RootLayOut
  src/app/layout.tsx
Labels: feat, FE

#27 ✨ feat(ProductList): add gnb/TabMenu Component
  src/app/layout.tsx
  src/app/productList/page.tsx
  src/components/gnb/Header.tsx
  src/components/gnb/TabMenu.tsx
  src/components/ui/button.tsx
Labels: feat, refactor, component

#30 Chore(ai)/26-add-coderabbit-ruleset
  .coderabbit.yaml
  src/app/globals.css
  src/app/modal-test/page.tsx
  src/app/productList/page.tsx
  src/components/gnb/HeaderMenu.tsx
  src/components/gnb/TabMenu.tsx
  src/components/ui/Dropdown-Menu.tsx
  src/components/ui/NumberInput.tsx
  src/components/ui/ProfileUploader.tsx
  src/components/ui/TextIcon.tsx
  src/components/ui/TextOutlined.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/components/ui/modal/BaseFormModal.tsx
  src/components/ui/modal/Modal.tsx
  src/stores/.gitkeep
  src/types/.gitkeep
Labels: chore, FE

#31 ♻️ refact(Tabmenu): refactoring TabMenu Category Object
  src/components/gnb/TabMenu.tsx
Labels: refactor

#33 ♻️ refact(TabMenu): add page state to TabMenu Component
  src/app/playground/mock.tsx
  src/app/productList/page.tsx
  src/components/gnb/TabMenu.tsx
  src/components/productList/SortDropDown.tsx
Labels: refactor

#34 ✨ feat(productList): add ProductCard & SortDropDown Component
  src/app/globals.css
  src/app/playground/mock.tsx
  src/app/productList/page.tsx
  src/components/gnb/Header.tsx
  src/components/gnb/TabMenu.tsx
  src/components/productList/CardList.tsx
  src/components/productList/ProductCard.tsx
  src/components/productList/SortDropDown.tsx
  src/components/ui/card.tsx
Labels: feat, FE, component, page

#37 🔧 chore(husky): CI 환경에서 nvm을 사용하도록 패키지 매니저 설정 수정
  .husky/set-node.sh
Labels: chore, FE

#42 ♻️ refact(ProductList): add SearchParams
  src/app/playground/mock.tsx
  src/app/productList/page.tsx
  src/components/gnb/TabMenu.tsx
  src/components/productList/CardList.tsx
  src/components/productList/ProductCard.tsx
  src/components/productList/SortDropDown.tsx
Labels: refactor

#46 Chore(deps)/38 add eslint plugins
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.tsx
  src/app/globals.css
  src/app/history/components/HistoryTable.tsx
  src/app/history/components/SummaryCards.tsx
  src/app/history/page.tsx
  src/app/layout.tsx
  src/app/modal-test/page.tsx
  src/app/productList/page.tsx
  src/components/gnb/Header.tsx
  src/components/gnb/HeaderMenu.tsx
  src/components/gnb/TabMenu.tsx
  src/components/productList/CardList.tsx
  src/components/productList/ProductCard.tsx
  src/components/productList/SortDropDown.tsx
  src/components/ui/Button.tsx
  src/components/ui/Card.tsx
  src/components/ui/Cards.tsx
  src/components/ui/Dialog.tsx
  src/components/ui/Dropdown-Menu.tsx
  src/components/ui/Input.tsx
  src/components/ui/Input_auth.tsx
  src/components/ui/NavigationMenu.tsx
  src/components/ui/NumberInput.tsx
  src/components/ui/ProfileUploader.tsx
  src/components/ui/ResponsiveImage.tsx
  src/components/ui/Select.tsx
  src/components/ui/Table.tsx
  src/components/ui/TextArea.tsx
  src/components/ui/TextBubble.tsx
  src/components/ui/TextIcon.tsx
  src/components/ui/TextOutlined.tsx
  src/components/ui/card.tsx
  src/components/ui/cards.tsx
  src/components/ui/modal/BaseFormModal.tsx
  src/components/ui/modal/InviteMemberModal.tsx
  src/components/ui/modal/MemberRoleChangeModal.tsx
  src/components/ui/modal/Modal.tsx
  src/components/ui/modal/ProductEditModal.tsx
  src/components/ui/modal/ProductFormModal.tsx
  src/components/ui/table.tsx
  src/hooks/useWindowSize.ts
  src/lib/constants.ts
  src/lib/utils.ts
Labels: chore, FE

#48 Chore(lint)/47-mitigate-lint-rules
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
Labels: chore, FE

#51 feat(ProductDetail):add ProductDetail(미완)
  .gitignore
  src/app/productList/[id]/page.tsx
  src/components/gnb/Header.tsx
  src/components/gnb/TabMenu.tsx
  src/components/productList/CardList.tsx
Labels: feat, component, page

#56 ✨ feat(ProductList): FloatingButton 상품 등록 플로팅 버튼 추가
  package.json
  src/app/globals.css
  src/app/productList/[id]/page.tsx
  src/app/productList/page.tsx
  src/components/productList/FloatingButton.tsx
  src/components/productList/ProductCard.tsx
  src/components/productList/SortDropDown.tsx
Labels: component

#57 ✨ feat(ProductList): 더보기 버튼 컴포넌트 추가
  src/app/productList/page.tsx
  src/components/productList/MoreButton.tsx
Labels: component

#59 ✨ feat(ProductEntry): add ProductEntry(진행 상황)
  src/app/playground/entryMock.tsx
  src/app/productEntry/page.tsx
  src/components/gnb/Header.tsx
  src/components/productList/SortDropDown.tsx
Labels: component, page

#61 ✨ feat(ProductList): add FetchProducts func.
  next.config.ts
  public/img/card/WarningImage.svg
  src/app/globals.css
  src/app/playground/page.tsx
  src/app/productList/[id]/page.tsx
  src/app/productList/page.tsx
  src/components/gnb/TabMenu.tsx
  src/components/productList/CardList.tsx
  src/components/productList/ProductCard.tsx
  src/components/productList/SortDropDown.tsx
Labels: feat

#63 Chore(deps)/62-bump-dependencies
  package.json
  pnpm-lock.yaml
  src/app/auth/login/page.tsx
  src/app/modal-test/page.tsx
  src/app/playground/page.tsx
  src/app/productEntry/page.tsx
  src/app/productList/[id]/page.tsx
  src/app/productList/page.tsx
  src/components/gnb/TabMenu.tsx
  src/components/productList/CardList.tsx
  src/components/productList/FloatingButton.tsx
  src/components/productList/MoreButton.tsx
  src/components/productList/ProductCard.tsx
  src/components/productList/ProductMenu.tsx
  src/components/productList/SortDropDown.tsx
  src/components/ui/NumberInput.tsx
  src/components/ui/modal/PurchaseItem.tsx
  src/components/ui/modal/PurchaseRequestModal.tsx
Labels: chore, FE

#66 상품 상세 페이지 api 연동 완료
  src/app/not-found.tsx
  src/app/productList/[id]/page.tsx
  src/app/productList/layout.tsx
  src/app/productList/page.tsx
  src/components/gnb/Header.tsx
  src/components/gnb/TabMenu.tsx
  src/components/productList/EmptyImage.tsx
  src/components/productList/ProductCard.tsx
  src/components/productList/ProductProvider.tsx
  src/components/productList/SortDropDown.tsx
  src/hooks/product/useFetchProduct.tsx
Labels: feat, component, page

#67 ➕ chore: install framer-motion
  package.json
  pnpm-lock.yaml
  src/app/productList/[id]/page.tsx
  src/app/productList/layout.tsx
  src/app/productList/page.tsx
  src/components/gnb/TabMenu.tsx
  src/components/productList/CardList.tsx
  src/components/productList/ProductProvider.tsx
  src/components/productList/SortDropDown.tsx
  src/hooks/product/useFetchProduct.tsx
Labels: deps, FE

#70 💄 UX(ProductDetail): UX 개선
  src/app/productList/[id]/detail/page.tsx
  src/app/productList/page.tsx
  src/components/gnb/TabMenu.tsx
  src/components/productList/CardList.tsx
  src/components/productList/ProductCard.tsx
Labels: ui/ux

#79 Feature/add table card components
  src/app/history/[id]/page.tsx
  src/app/history/components/HistoryTable.tsx
  src/app/history/components/PurchaseApprovalInfo.tsx
  src/app/history/components/PurchaseItemList.tsx
  src/app/history/components/PurchaseRequestInfo.tsx
  src/app/history/components/PurchaseSummary.tsx
  src/app/history/page.tsx
  src/app/request/[id]/page.tsx
  src/app/request/components/OrderTable.tsx
  src/app/request/page.tsx
  src/components/gnb/Header.tsx
  src/components/gnb/HeaderMenu.tsx
  src/components/ui/modal/BaseFormModal.tsx
  src/components/ui/modal/purchaseApprovalModal.tsx
  src/lib/api/orders.ts
Labels: feat, FE, component

#80 상품상세: 상품 삭제 모달 구현 완료
  src/app/productList/[id]/detail/page.tsx
  src/app/productList/page.tsx
  src/components/gnb/Header.tsx
  src/components/productList/ProductCard.tsx
  src/components/ui/Toast/Toast.tsx
  src/components/ui/modal/ProductDeleteModal.tsx
  src/hooks/product/useProductDelete.tsx
Labels: component

#83 Feature/product entry
  src/app/playground/entryMock.tsx
  src/app/productEntry/page.tsx
  src/app/productList/page.tsx
  src/components/productEntry/EntryHeader.tsx
  src/components/productEntry/EntryList.tsx
  src/components/ui/Pagination.tsx
Labels: component, page
