Repository snack-25/front, pull requests merged in 2025-04, with the labels that each got.

#90 Feature/product entry
  src/app/productList/[id]/detail/page.tsx
  src/app/productList/page.tsx
  src/components/gnb/TabMenu.tsx
  src/components/productList/ProductCard.tsx
  src/components/productList/ProductNotAuth.tsx
  src/hooks/product/useCategory.tsx
Labels: refactor

#94 Fix/린트 에러 수정
  src/app/api/auth/useAuthStore.ts
  src/app/api/instance.tsx
  src/app/auth/login/page.tsx
  src/app/auth/signup/Invitation.tsx
  src/app/auth/signup/SignupContent.tsx
  src/app/auth/signup/SuperAdmin.tsx
  src/app/auth/signup/page.tsx
  src/app/history/[id]/page.tsx
  src/app/history/components/HistoryTable.tsx
  src/app/history/components/PurchaseApprovalInfo.tsx
  src/app/history/components/PurchaseItemList.tsx
  src/app/history/components/PurchaseRequestInfo.tsx
  src/app/history/components/PurchaseSummary.tsx
  src/app/history/page.tsx
  src/app/layout.tsx
  src/app/management/budget/page.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/productEntry/ProductEntry.tsx
  src/app/productEntry/page.tsx
  src/app/productList/ProductList.tsx
  src/app/productList/[id]/detail/page.tsx
  src/app/productList/page.tsx
  src/app/request/[id]/page.tsx
  src/app/request/components/OrderTable.tsx
  src/app/request/components/StatusModal.tsx
  src/app/request/page.tsx
  src/components/gnb/Header.tsx
  src/components/gnb/ParentTab.tsx
  src/components/gnb/SubTab.tsx
  src/components/gnb/TabMenu.tsx
  src/components/productEntry/EntryList.tsx
  src/components/productList/CardList.tsx
  src/components/productList/EmptyImage.tsx
  src/components/productList/ProductCard.tsx
  src/components/productList/ProductMenu.tsx
  src/components/ui/Input_auth.tsx
  src/components/ui/Pagination.tsx
  src/components/ui/SortDropDown.tsx
  src/components/ui/Toast/Toast.tsx
  src/components/ui/modal/Modal.tsx
  src/components/ui/modal/ProductDeleteModal.tsx
  src/components/ui/modal/purchaseApprovalModal.tsx
  src/hooks/product/useCategory.tsx
  src/hooks/product/useDetail.tsx
  src/hooks/product/useFetchProduct.tsx
  src/hooks/product/useProductDelete.tsx
  src/lib/api/orders.ts
  src/lib/constants.ts
Labels: bug, help wanted, refactor, chore, discussion, FE

#100 feat(useAuthStore): add isHydrated state
  src/app/api/auth/useAuthStore.ts
  src/app/productEntry/ProductEntry.tsx
  src/app/productEntry/page.tsx
  src/app/productList/ProductList.tsx
  src/components/gnb/Header.tsx
  src/components/gnb/TabMenu.tsx
  src/hooks/product/useCategory.tsx
  src/hooks/product/useProductDelete.tsx
Labels: feat

#109 ⬆️ fix(deps): 패키지 버전 업데이트 및 API URL 환경변수 적용
  package.json
  pnpm-lock.yaml
  src/app/api/auth/useAuthStore.ts
  src/app/api/instance.ts
  src/app/auth/login/page.tsx
  src/app/auth/signup/SignupContent.tsx
  src/app/management/profile/page.tsx
  src/app/management/users/page.tsx
  src/app/modal-test/page.tsx
  src/app/page.tsx
  src/app/productEntry/ProductEntry.tsx
  src/app/productEntry/page.tsx
  src/app/productList/ProductList.tsx
  src/app/productList/[id]/detail/page.tsx
  src/app/request/[id]/page.tsx
  src/app/request/components/OrderTable.tsx
  src/app/request/components/StatusModal.tsx
  src/app/request/page.tsx
  src/components/gnb/ManagementTabMenu.tsx
  src/components/gnb/TabMenu.tsx
  src/components/productList/CardList.tsx
  src/components/ui/CategorySelect.tsx
  src/components/ui/modal/BaseFormModal.tsx
  src/components/ui/modal/InviteMemberModal.tsx
  src/components/ui/modal/ProductFormModal.tsx
  src/components/ui/modal/purchaseApprovalModal.tsx
  src/components/wrappers/ClientWrapper.tsx
  src/hooks/product/useCategory.tsx
Labels: chore, deps, FE

#141 🐛 fix:장바구니- 예산조회 수정
  src/app/cart/[cartId]/page.tsx
  src/components/cartItems/cartItem.tsx
  src/components/cartItems/cartSummary.tsx
  src/lib/api/cart.ts
  src/types/cart.ts
Labels: FE, api

#180 랜딩 페이지 반응형 완료, UI 개선
  pnpm-lock.yaml
  src/app/auth/api.tsx
  src/app/auth/layout.tsx
  src/app/auth/login/page.tsx
  src/app/auth/signup/Invitation.tsx
  src/app/auth/signup/SignupContent.tsx
  src/app/auth/signup/SuperAdmin.tsx
  src/app/auth/useAuthStore.ts
  src/app/cart/[cartId]/page.tsx
  src/app/globals.css
  src/app/history/[id]/page.tsx
  src/app/history/components/HistoryTable.tsx
  src/app/history/components/SummaryCards.tsx
  src/app/history/page.tsx
  src/app/layout.tsx
  src/app/management/budget/page.tsx
  src/app/management/layout.tsx
  src/app/management/profile/page.tsx
  src/app/management/users/page.tsx
  src/app/my-request/[id]/page.tsx
  src/app/my-request/components/CancelModal.tsx
  src/app/my-request/components/MyRequestTable.tsx
  src/app/my-request/page.tsx
  src/app/order-request/[orderRequestId]/page.tsx
  src/app/order/[orderId]/page.tsx
  src/app/page.tsx
  src/app/productList/ProductList.tsx
  src/app/productList/[id]/detail/page.tsx
  src/app/productList/page.tsx
  src/app/request/[id]/page.tsx
  src/app/request/components/OrderTable.tsx
  src/app/request/page.tsx
  src/components/cartItems/cartItem.tsx
  src/components/cartItems/cartSummary.tsx
  src/components/gnb/Header.tsx
  src/components/gnb/HeaderMenu.tsx
  src/components/gnb/TabMenu.tsx
  src/components/mobileLoginBox/MobileLoginBox.tsx
  src/components/productList/ProductListWrapper.tsx
  src/components/tooltip/CustomTooltip.tsx
  src/components/ui/Button.tsx
  src/components/ui/CategorySelect.tsx
  src/components/ui/modal/MemberRoleChangeModal.tsx
  src/components/ui/modal/OrderRequestModal.tsx
  src/components/ui/modal/purchaseApprovalModal.tsx
  src/hooks/order/useOrder.ts
  src/hooks/orderRequest/useOrderRequest.ts
  src/hooks/product/useCategory.tsx
  src/lib/utils/useToastWithAutoClose.tsx
  src/types/order.ts
  src/types/user.ts
Labels: refactor, FE

#193 ✨ feat: 실제 상품 API 연동
  src/app/page.tsx
  src/app/productEntry/ProductEntry.tsx
  src/components/productEntry/EntryList.tsx
Labels: FE, api

#209 🚑️ fix: Refactor category hooks to filter by company ID
  src/hooks/product/useCategory.tsx
Labels: FE
